#
# Module manifest for module 'PSGet_PoShGroupPolicy'
#
# Generated by: Dave Carroll
#
# Generated on: 3/18/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PoShGroupPolicy.psm1'

# Version number of this module.
ModuleVersion = '0.4'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'fa6fcad4-9c3f-4258-8475-bbf11060b779'

# Author of this module
Author = 'Dave Carroll'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2018 Dave Carroll. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module to assist with Group Policy'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @('GroupPolicy')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @('')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-GPSetting'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'PoShGroupPolicy.psd1', 'PoShGroupPolicy.psm1',
            'en-US\about_PoShGroupPolicy.help.txt', 
            'Private\Get-GPKnownFolderId.ps1', 'Public\Get-GPSetting.ps1',
            'TypeData\PoShGroupPolicy.Format.ps1xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        #Category of this module
        Category = 'Group Policy'

        #RequireLicenseAcceptance of this module
        RequireLicenseAcceptance = 'False'

        #IsPrerelease of this module
        IsPrerelease = 'True'
                
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PoshGroupPolicy','GroupPolicy','Group-Policy','PowerShell','GPO','AzureAutomationNotSupported'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/thedavecarroll/PoShGroupPolicy/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/thedavecarroll/PoShGroupPolicy'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = ''

        # External dependent modules of this module
        ExternalModuleDependencies = 'GroupPolicy'

    } # End of PSData hashtable
    
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

